[all_nodes]
compute1 ansible_python_interpreter=/usr/bin/python3
compute2 ansible_python_interpreter=/usr/bin/python3
compute3 ansible_python_interpreter=/usr/bin/python3
compute4 ansible_python_interpreter=/usr/bin/python3

[head]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
