# BASIC CONFIGURATION
ClusterName=cluster
SlurmctldHost=head

# MPI and Task Plugins
MpiDefault=pmi2
ProctrackType=proctrack/cgroup
TaskPlugin=task/affinity,task/cgroup

# JOB ACCOUNTING
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30

# STATE & PID FILES
ReturnToService=1
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

# COMMUNICATION
SlurmctldPort=6817
SlurmdPort=6818
SlurmUser=slurm

# STATE SAVE AND LOGGING
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

# DEBUG LEVELS
SlurmctldDebug=info
SlurmdDebug=info

# SCHEDULER CONFIG
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

# ACCOUNTING
AccountingStorageHost=head
AccountingStoragePort=6819
AccountingStorageType=accounting_storage/slurmdbd
JobCompType=jobcomp/none

# TIMEOUTS & LIMITS
SlurmctldTimeout=120
SlurmdTimeout=300
MinJobAge=300
KillWait=30
InactiveLimit=0
Waittime=0

# NODE AND PARTITION DEFINITIONS
NodeName=compute[1-4] CPUs=4 Boards=1 Sockets=4 CoresPerSocket=1 ThreadsPerCore=1 RealMemory=3900 State=UNKNOWN
PartitionName=gpu Nodes=ALL Default=YES MaxTime=INFINITE State=UP
