- name: Ensure munge is running (required for Slurm)
  ansible.builtin.service:
    name: munge
    state: started
    enabled: true

- name: Ensure MariaDB is running
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true

- name: Create slurm accounting database via Unix socket
  community.mysql.mysql_db:
    name: slurm_acct_db
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create 'slurm' DB user with privileges via Unix socket
  community.mysql.mysql_user:
    name: slurm
    password: "lcilab2023"
    priv: "slurm_acct_db.*:ALL,GRANT"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock


- name: Ensure /var/log/slurm exists
  ansible.builtin.file:
    path: /var/log/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Ensure /run/slurm exists
  ansible.builtin.file:
    path: /run
